---
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - sudo apt-get remove --purge -s 'mysql*'
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log
install:
  - pip install ansible
  - ansible-galaxy install Ansibles.mysql
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check role.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv role.yml
